import localFont from "next/font/local";
import "./globals.css";
import {Gluten, Yatra_One} from "next/font/google"

// gluten is a function
// it takes an options object as an arugment
export const gluten = Gluten({
  weight: '400',
  subsets: ['latin']
})

// if you want be able to apply your font through css 
// give it a variable name
// the variable name need sto start with --font
// and then add to the body.
// so its accessible to the rest of our css.
const yatara_one = Yatra_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yatara_one'
})


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gluten.className} ${yatara_one.variable}`}>
        {children}
      </body>
    </html>
  );
}
